include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # 允许在插件代码中使用 print 风格调试工具
    avoid_print: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
